import { test, expect } from '@playwright/test'
for (const language of ['en', 'de']) {
  test(`dummy preview validates without requests or storage (${language})`, async ({ page }) => {
    const requests = []
    page.on('request', request => { if (request.url().includes('/api/newsletter/')) requests.push(request.url()) })
    await page.addInitScript(lang => {
      localStorage.setItem('twiiiins-website-language', lang)
      localStorage.setItem('twiiiins-cookie-preferences', JSON.stringify({ version: 1, media: false, savedAt: Date.now() }))
    }, language)
    await page.goto('/contact')
    const signup = page.locator('.newsletter-signup')
    const snapshot = () => page.evaluate(() => JSON.stringify({ local: { ...localStorage }, session: { ...sessionStorage }, cookies: document.cookie }))
    const before = await snapshot()
    await expect(signup).toContainText(language === 'en' ? 'Preview only' : 'Nur Vorschau')
    const email = signup.locator('input[type=email]')
    const button = signup.getByRole('button')
    await email.fill('invalid')
    await button.click()
    expect(await email.evaluate(input => input.validity.valid)).toBe(false)
    await email.fill('preview@example.com')
    await button.click()
    expect(await signup.getByRole('checkbox').evaluate(input => input.validity.valid)).toBe(false)
    await signup.getByRole('checkbox').check()
    await button.click()
    await expect(signup.getByRole('status')).toContainText(language === 'en' ? 'Preview complete' : 'Vorschau abgeschlossen')
    expect(requests).toEqual([])
    expect(await snapshot()).toBe(before)
    await expect(email).toHaveValue('')
    await expect(signup.getByRole('checkbox')).not.toBeChecked()
  })
}


test('newsletter studio renders attachments and both languages without API writes', async ({ page }, testInfo) => {
  const writes = []
  page.on('request', request => { if (request.method() !== 'GET' && request.method() !== 'HEAD') writes.push(request.url()) })
  await page.addInitScript(() => localStorage.setItem('twiiiins-cookie-preferences', JSON.stringify({ version: 1, media: false, savedAt: Date.now() })))
  await page.goto('/dev/newsletter')
  await expect(page.locator('.navbar')).toHaveCount(0)
  await page.getByRole('button', { name: '예시 내용 채우기' }).click()
  await expect.poll(() => page.locator('.photos img').first().evaluate(img => img.naturalWidth)).toBeGreaterThan(0)
  const frame = page.frameLocator('iframe[title="발송 메일 실시간 미리보기"]')
  await expect(frame.getByRole('heading', { level: 1 })).toHaveText('SOUND IN MOTION')
  await expect(frame.locator('img')).toHaveCount(1)
  await expect.poll(() => frame.locator('img').evaluate(img => img.naturalWidth)).toBeGreaterThan(0)
  await expect(frame.getByRole('link', { name: 'Explore the performance' })).toHaveAttribute('href', 'https://twiiiins.com/concerts')
  await page.getByLabel('영어 제목').fill('SOUND IN MOTION / A LONG CONTEMPORARY PERFORMANCE TITLE THAT WRAPS ACROSS SEVERAL LINES')
  await expect(frame.getByRole('heading', { level: 1 })).toContainText('A LONG CONTEMPORARY')
  await page.getByRole('button', { name: '모바일 375' }).click()
  await expect(frame.locator('body')).toHaveCSS('background-color', 'rgb(5, 5, 5)')
  const overflow = await frame.locator('html').evaluate(el => el.scrollWidth > el.clientWidth)
  expect(overflow).toBe(false)
  await page.getByLabel('사진 추가').setInputFiles({ name: 'extra.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a/RsAAAAASUVORK5CYII=', 'base64') })
  await expect(frame.locator('img')).toHaveCount(2)
  await expect(frame.locator('img').nth(1)).toHaveAttribute('src', /^blob:/)
  await page.getByRole('button', { name: '미리보기 Deutsch', exact: true }).click()
  await expect(frame.getByRole('heading', { level: 1 })).toHaveText('KLANG IN BEWEGUNG')
  await expect(frame.getByText('Abmelden (Vorschau)', { exact: true })).toBeVisible()
  await expect(frame.getByRole('link', { name: 'Abmelden (Vorschau)' })).toHaveCount(0)
  await page.getByLabel('안내 버튼 주소').fill('http://insecure.example.com')
  await expect(page.getByRole('alert')).toContainText('미리보기를 갱신하지 못했습니다')
  await expect(frame.getByRole('heading', { level: 1 })).toHaveText('KLANG IN BEWEGUNG')
  await page.getByLabel('안내 버튼 주소').fill('https://twiiiins.com/concerts')
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(page.locator('.mail-preview')).toContainText('입력한 내용이 자동으로 반영됩니다.')
  await page.locator('.mail-preview').screenshot({ path: testInfo.outputPath('newsletter-email.png') })
  await page.screenshot({ path: testInfo.outputPath('newsletter-studio.png'), fullPage: true })
  expect(writes).toEqual([])
  await page.getByRole('button', { name: '초기화', exact: true }).click()
  await expect(frame.locator('img')).toHaveCount(0)
  await expect(page.getByLabel('영어 제목')).toHaveValue('')
})
