spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/twiiiins_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

logging:
  level:
    com.twiiiins: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  file:
    upload-dir: uploads-dev
